rvm/rvm1-ansible

README.md
defaults/main.yml
tasks/rvm.yml

On Ubuntu 14.04 without sudo, the default autolibs mode 3 causes the
role to hang when trying to install ruby-1.9.3-p0.

Allow users to configure the autolibs mode of installed rvms.

---

tasks/rvm.yml

I was having some issues when choosing a regular user for rvm1_user where the `.rvm` directory in `/home/{{rvm1_user}}/` would be owned by `root`. The issue would cause an error when the role would try to install rubies. The changes in this PR were the things that I needed to change for it to work but I am not sure if they break other use cases. This is also my second week doing any ansible so let me know if I did anything silly.
- use rvm1_user for the gpg keys
- use rvm1_user when installing rvm
- use rvm1_user when updating rvm
- use rvm1_user when configuring rvm

fixes the rvm install when rvm1_user is specified

---

README.md
defaults/main.yml
tasks/rubies.yml

This commit adds a var called `rvm_1_ruby_install_flags`, so you can pass `./configure` flags such as `--with-jemalloc` to `rvm install`.

Add option for passing ruby install flags

---

tasks/rubies.yml

Since bundler is not a default gem as of RVM 1.26.11, it needs to be installed. Fixes #35

Installing bundler

---

tasks/rubies.yml

We should check gem list for specified ruby, not a default system's one.

Fix bundler installation shell command

---

tasks/rubies.yml

We found an issue with the gem and bundler directory location just as mentioned in this issue #71 , 'update #46' 
Before the fix bundler gem was installed in default gemset - this is only available when you run "rvm use ruby-2..2.2" but we need it in any gemset: "rvm use ruby@gemset" and this is achieved by installing bundler gem in the "@global" gemset that is inherited by all the gemsets on given ruby.

This fixes the location of the bundler pointing to the global ruby version

---

defaults/main.yml

The rvm repository on GitHub has moved. Update the installer path to
this new location.

update rvm installer path

---

.travis.yml
tasks/rubies.yml

Fix for #84 
- Add `sudo_user` directive to tasks that install rubies and gems
```
root@ip-10-152-153-205:/opt/ansible# sudo su - jenkins
jenkins@ip-10-152-153-205:~$ ls -ld .rvm
drwxr-xr-x 25 jenkins jenkins 4096 Feb  9 10:38 .rvm
jenkins@ip-10-152-153-205:~$ ls -l .rvm
total 120
drwxr-xr-x  2 jenkins jenkins 4096 Feb  9 10:39 archives
drwxr-xr-x  2 jenkins jenkins 4096 Feb  9 10:38 bin
drwxr-xr-x  3 jenkins jenkins 4096 Feb  9 10:39 config
drwxr-xr-x  3 jenkins jenkins 4096 Feb  9 10:38 contrib
drwxr-xr-x  2 jenkins jenkins 4096 Feb  9 10:38 docs
drwxr-xr-x  2 jenkins jenkins 4096 Feb  9 10:39 environments
drwxr-xr-x  2 jenkins jenkins 4096 Feb  9 10:38 examples
drwxr-xr-x  2 jenkins jenkins 4096 Feb  9 10:38 gem-cache
drwxr-xr-x  4 jenkins jenkins 4096 Feb  9 10:39 gems
drwxr-xr-x  4 …
```

[OI] Ensure installed rubies and gems are owned correctly by rvm1_user

---

defaults/main.yml
tasks/rubies.yml

Perhaps this should be changed to use the numeric IDs (0).  But, in BSD land group 0 is typically wheel (not root).

Parameterize superuser/group names

---

vars/main.yml

If 'rvm1_rubies' is a string with a single Ruby version (a common mistake), the role currently installs it correctly but subsequently fails to symlink the default wrappers; with this change it will instead correctly use the given version.

Accept 'rvm1_rubies' as a single string version

---

tasks/rvm.yml

GPG key import sometimes fail due to network partitions or errors on the
remote server. Retry the GPG key import up to 5 times if this happens,
so the playbook doesn't fail from temporary network issues.

retry gpg key import

---

tasks/rvm.yml

Step "Import GPG keys" always fails on our hardened ubuntu 14.04. Could be either the version of our ubuntu we are using, or the company firewall. Adding the alternative method to import GPG key in case first method fails.

Import GPG keys the other way

---

README.md

nfedyashev@MacPro : ~
[0] % ansible-galaxy install rvm_io.rvm1-ruby
- downloading role 'rvm1-ruby', owned by rvm_io
[WARNING]: - rvm_io.rvm1-ruby was NOT installed successfully: - sorry, rvm_io.rvm1-ruby was not found on https://galaxy.ansible.com.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
nfedyashev@MacPro : ~
[1] % ansible-galaxy install rvm_io.ruby
- downloading role 'ruby', owned by rvm_io
- downloading role from https://github.com/rvm/rvm1-ansible/archive/v1.3.9.tar.gz
- extracting rvm_io.ruby to /usr/local/etc/ansible/roles/rvm_io.ruby
- rvm_io.ruby was installed successfully

Fix ansible-galaxy installation parameter

---

tasks/rvm.yml

The ['get_url' module](http://docs.ansible.com/ansible/get_url_module.html) has a `mode` parameter which can be used instead of the 'Configure rvm installer' task.
This PR also fixes an issue in the when statement where `rvm_binary` is checked instead of `rvm_installer`

Use 'mode' parameter of 'get_url' module

---

README.md

One of the examples was missing some commas and resulted in invalid YAML

Add missing commas to README

---

.travis.yml
meta/main.yml
tasks/main.yml
tests/root.yml
tests/user.yml

Ansible 2.4 deprecated the use of 'include' for playbook includes with
plans to remove it completely in version 2.8. Replace the places where
it was used with the new 'import_playbook' and update the minimum
ansible version.
See https://github.com/rvm/rvm1-ansible/issues/169

Replace include with import_playbook to address deprecation in 2.4

---

.travis.yml

It takes long enough to build the 6 different distro containers used for
tests that Travis is killing the build during docker-compose up. In the
Travis output, there's a message "No output has been received in the
last 10m0s", which suggests it's killing the job early in part because
we're sending all docker-compose output to /dev/null. Try showing all of
that output in the hopes of improving build reliability.

Show docker-compose output in Travis to address build timeouts

---

tasks/rvm.yml

- Solved issue https://github.com/rvm/rvm1-ansible/issues/187 .
This is the recommended way to execute `gpg` when not on a real terminal.

Solved error during GPG execution.

---

CHANGELOG.md
tasks/rubies.yml

This PR is about fixing some warning messages showing up in the console when running the role with ansible ≥ 2.8

Fixes bare variables in conditionals (deprecation warnings with Ansible 2.8+)

---

CHANGELOG.md
tasks/rubies.yml

I think checking condition like this: ```rvm1_rubies | bool``` doesn't work for array. It is always false.
This causes an error:
```
"stderr": "/bin/sh: /home/user/.rvm/wrappers//gem: not found"
```
Looks like checking using `| length` works for arrays but it is also works for strings.

Fix boolean values when checking array

---

CHANGELOG.md
tasks/rubies.yml

This fixes issues introduced by https://github.com/rvm/rvm1-ansible/commit/deb1d3e6212d9ec6605510554bf268d18688513e as described by #209. The linked commit resolved warnings about bare variables in conditionals, but ended up breaking the conditional logic by misusing the `bool` filter. The `bool` filter returns `true` for vars set to ‘yes’, ‘on’, ‘1’, and ‘true’, and returns `false` otherwise, see https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html.

update tasks/rubies.yml - fix bool misuse

---

.travis.yml
CHANGELOG.md
README.md
tests/assertions.yml
tests/docker-compose.yml
tests/dockerfiles/centos8/Dockerfile
tests/dockerfiles/debian10/Dockerfile
tests/dockerfiles/ubuntu18/Dockerfile
tests/dockerfiles/ubuntu20/Dockerfile
tests/group_vars/all
tests/inventory
tests/root.yml
tests/user.yml

As a prerequisite to further works (e.g. rebasing #52), I propose here to refresh the test environment with following changes:
- Replace outdated versions of CentOS, Ubuntu and Debian by new versions
- Modify `tests/assertions.yml` to provide stronger validation of **rvm behaviours**
- Integrate `tests/root.yml`  in Travis CI build
- Use latest versions of Ruby, Ansible and docker-compose in Travis CI build environment

Update and enhance the test environment

---

CHANGELOG.md
tasks/rubies.yml

I think this should help clean up a bit and resolves #218.

Refactor rubies install and remove tasks

---

CHANGELOG.md
tasks/rvm.yml

Implements the suggested fix from #155 in order to enable rvm to install properly on CentOS 8 (and hopefully 7 and a few other distro variations as well).
Fixes #155

Fix RHEL 7 & 8 based distros to work around /tmp execution issues

---

README.md
defaults/main.yml
tasks/rubies.yml

Symlinks are already disabled for user installs. For cases where
multiple system-wide Ruby versions are provided by RVM, add an option to
disable symlinking of binaries to the system path.
Default `rvm1_symlink` to `true` to maintain existing behavior parity.

Add option to disable binary symlink
