rvm/rvm1-ansible

.travis.yml
meta/main.yml
tasks/rubies.yml
tests/test.yml

See https://github.com/rvm/rvm1-ansible/pull/59 for discussion.

Fix Bundler symlinking on system path

---

tasks/rubies.yml

* Set defaults and always_run to support --check mode.

Fix issue #78.

---

tasks/rubies.yml
tasks/rvm.yml

Update become method

---

README.md

Improved some documentation as per #75 requested. 
Also went through the readme and applied the proper code highlighting.

Rjrobinson patch 2

---

tasks/main.yml
tasks/rubies.yml
tasks/rvm.yml

Become and become_user vars moved to main.yml file to reduce the duplicity of the lines.

Become and become_user moved to main.yml file

---

README.md
defaults/main.yml
tasks/rubies.yml
vars/main.yml

Add `rvm1_bundler_install` variable to control bundler installation

Add possibility to skip bundler installation

---

.travis.yml
defaults/main.yml
tests/test.yml

Make default rvm1_user as a non root user, and run the test suite with newer versions of ruby.

Default non root user

---

README.md

The current URL does not work anymore

Fix Ansible Galaxy URL

---

README.md

Update readme with single user installation.

Update readme with single user installation

---

README.md

As mentioned by @thbar in #117, the URL changed again

Fix Ansible Galaxy URL again

---

README.md

There are some inconsistencies in the README after the change to make user install default
I tried to address them, and clarify/fix some other things while I was at it.

Improve system-wide installation instructions

---

.travis.yml
meta/main.yml
tasks/rubies.yml

Bump ansible version from 2.0 to 2.2 to keep updated the role with the last ansible releases.

Bump ansible version from 2.0 to 2.2

---

tasks/rvm.yml

skip the gpg key import tasks in check mode

---

tasks/rubies.yml

…ezes asking for sudo password

Fixes #127: Unable to install for single user on a fresh machine: fre..

---

tasks/rubies.yml

This reverts commit ed65673e2edfc5a1fdecb6285155b2170b5c0528, reversing
changes made to 0df684cd94553ec9e96aa13a2542e1e701cef62f.

Revert "Merge pull request #141 from jogaco/master"

---

.travis.yml
README.md

Show badge for master branch in the README and add badge in the ansible galaxy page.

Show badge for master branch and add badge in ansible galaxy

---

meta/main.yml

Fixes #148: Make sure Ansible Galaxy can import role.

---

vars/main.yml

Fixes #157: Remove missing testrb from symlinked binaries.

---

README.md

Update the README to reflect galaxy package name change reported in
https://github.com/rvm/rvm1-ansible/issues/179.

Update README to reflect change to galaxy package name

---

defaults/main.yml

Addresses https://github.com/rvm/rvm1-ansible/issues/184

Updated to use the full set of GPG keys as described on rvm.io

---

CHANGELOG.md

This fixes #209 (corrected via #207).

Update changelog to advertise fix for rubies installation blocker
